### ISSUE TITLE
SAML Service Provider SSO

### ISSUE THREAD

**Issue by hamish-tushar** [i8beef/SAML2#14]
HI,
I want to use your library to write multiple service providers for my clients (clients have their own IDP's) which the user will enter details about on my website before using SSO. The client will provide the login and logout urls, the certificates he got from idp, etc. When the user tries to login to my website from their intranet, I need to initiate the SAML request to their IDP. I just want to make sure this use case can be covered by this library and Also where can i find some sample code to start using the lib.

**Comment by i8beef** [comment]
Not sure I follow. This library will allow a single SP to integrate with one or more IDPs. I'm unsure what "multiple service providers" means in this case, since there can be only one here. If you have multiple SP's, each SP would be a separate integration with the IDP, which could be accomplished using this library.

If you are saying that you need to allow dynamic selection of WHICH IDP / SAML config to use for a specific user based on something outside of this library, that's different. This library is geared toward a simpler case of providing SSO for a single application (as a whole) to a single identity provider. If you were running an app per client in this case, that'd work, but if your app is multi-tenant and you are trying to introduce a different auth method per client, I'm unsure if this would be helpful to you. I think you'd have to rip apart the library to build something quite custom out of it.

As the readme says, everything should be fully documented in the [Wiki](https://github.com/i8beef/SAML2/wiki). There are no sample projects with this library.

**Comment by hamish-tushar** [comment]
Thanks Michael to for getting back. Yes you are absolutely right. I have a web application where in we need to support SSO for enterprises. Since each client(lets each enterprise)  will have their own IDP, we want to support multiple IDP all using my web app as SP. SO basically supporting multi tenancy.
SO i give the user the chance to provide login and logout url and upload certificates from the IDPS using your library and then initiate SAML for the user.

Is this possible? Looking from your response above seems like this is a use case that can be supported.

**Comment by i8beef** [comment]
Not easily. This library right now assumes a static configuration. While it DOES support run-time IDP SELECTION by passing a request value as part of the redirect to the sign-on handler ("cidp"), it assumes that the metadata for said IDP is already loaded into the static SAML2 configuration object, which happens only at app start through the web.config configuration providers. Ergo, you'd have to modify the web.config every time someone wants to add a new IDP. 

I don't think the configuration story is going to support your needs, and even if you could find a way to inject IDPs at runtime (something like changing your auth redirect to read user configuration, then push dynamic IDPs into the config object and redirect to sign-on handler?) it would be terribly inefficient, and I wouldn't recommend it.

You could take this library and gut it, implement your own handlers in a more app specific way and gut the configuration stuff to use your own methods, but I don't think it could be shoehorned into a multi-tenant app the way your attempting. You might be able to reuse parts of it, but I'd think you'd need to rewrite all of the handlers at a minimum, and the whole configuration layer.
