### ISSUE TITLE
SSO login with ADFS is not working.

### ISSUE THREAD

**Issue by SureshIndpro** [i8beef/SAML2#15]
Hello,
Thanks for this great plugin. I am a novice in implementing SSO. I used this plugin against a sample Identity provider which worked well. Now in the production environment, we need to connect to the ADFS server. 

When I place the ADFS metadata in the Metadata folder, the plugin throws error and points to the location in the IdP metadata file where the type is mentioned as fed:ApplicationServiceType. If I remove that type, the file signature is failing and could not use the file. 

Any example to work with ADFS available or how to fix this issue. Please help me to solve this. Thanks in advance.

**Comment by i8beef** [comment]
https://www.identityguy.com/articles/2010/7/2/federation-woes-adfs-v2-and-oracle.html

ADFS appends it's own non-standard SAML metadata to the metadata file, and because the metadata is signed, you can't just modify it without invalidating the signature. You are hitting the same issue this fella was.

Looking at the spec, what they are doing IS a valid extension of the specification. The code actually has a piece that should handle this, so I need to see where it's failing. 

It's a little hard to talk in generalities here, so if you can send a stack trace so I can see where its failing exactly, I might be able to help. Also, if you can send the metadata piece in question so I can validate it against whatever is failing (obviously, blank out any sensitive pieces).

**Comment by SureshIndpro** [comment]
Thanks for replying.

You are correct, I tried to change the file and it failed because of signing. 

I have traced the error and the error is happening during initializing the Saml20MetadataDocument. i.e. Saml20MetadataDocument constructor and in line 
Entity = Serialization.DeserializeFromXmlString<EntityDescriptor>(entityDescriptor.OuterXml);

It happens during deserializing from the xml because the tag RoleDescriptor xsi:type="fed:ApplicationServiceType"  and <RoleDescriptor xsi:type="fed:SecurityTokenServiceType" could not find the type expected and throwing the error:
The specified type was not recognized: name='ApplicationServiceType', namespace='http://docs.oasis-open.org/wsfed/federation/200706', at <RoleDescriptor xmlns='urn:oasis:names:tc:SAML:2.0:metadata'>.

Stack trace of inner exception:
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderEntityDescriptor.Read45_RoleDescriptor(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderEntityDescriptor.Read47_EntityDescriptor(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderEntityDescriptor.Read48_EntityDescriptor()

I have attached the edited metadata file of ADFS identity provider. Please guide to solve this issue.

[fs.ambea.se-edited.txt](https://github.com/i8beef/SAML2/files/986703/fs.ambea.se-edited.txt)

**Comment by i8beef** [comment]
So interestingly, this seems to be a problem for a lot of SAML only solutions and ADFS metadata. Funnily enough, there's a whole series of "how to integrate with X" articles here:

https://technet.microsoft.com/en-us/library/ff849212(v=ws.10).aspx

You might try some of these, where they remove the signature and modify the metadata document. The XML serializer, if the signature is missing, should deserialize it just fine... They are specifying a type that is not present in the schema that they ALSO reference, and so the deserialization fails. Why they do that... well.. I have no idea.

**Comment by i8beef** [comment]
Closing as known issue with ADFS generating non-standard SAML metadata. Documented solutions exist to remove signature and modify for inclusion.
