### ISSUE TITLE
How to add signing certificate for IdP?

### ISSUE THREAD

**Issue by Aravin** [i8beef/SAML2#19]
Hi Team,

How to add signing certificate for IdP?

**Comment by i8beef** [comment]
Signing certificate public key gets included as part of the IDP metadata document when it is imported. There is no configuration based method for specifying this at this time.

**Comment by Aravin** [comment]
Dear @i8beef , even if I didn't mention certificate in the metadata file. I am able to send the request.

**Comment by i8beef** [comment]
Not sure I understand. If your IDP isn't providing a metadata file with a signing certificate, then the library won't attempt to sign messages to the IDP. That isn't secure for a production environment, but it's a possible use case that we do cover.

Basically, both sides establish a contract for how they want messages sent via the exchanged metadata files. If the IDP isn't saying specifying that messages to / from it should be signed, then the library doesn't attempt to sign messages or verify signatures on received messages. 

I suggest that you familiarize yourself with the SAML spec a bit if you're looking to implement a SAML SP though, because things like this are basic security concerns of the implementation. If you don't have signing certs involved, for instance, then your implementation will be vulnerable to man in the middle type attacks, or message tampering.
