### ISSUE TITLE
Requset for saml:EncryptedAssertion 

### ISSUE THREAD

**Issue by flyinggiggs** [i8beef/SAML2#31]
Hi guys,

I am not sure if I am missing something, but I think "Assertion" class exists under Schema, but I can't find 
"EncryptedAssertion" class.
Can you guys advise me?

**Comment by i8beef** [comment]
https://github.com/i8beef/SAML2/blob/master/src/SAML2/Schema/Protocol/EncryptedAssertion.cs

**Comment by flyinggiggs** [comment]
Thank you i8beef. I just wonder if there are any example codes here using Assertions,Response, etc? I am trying to make a Saml2 request with this library and wonder if there is any good reference. 
Currently, I am trying to add EncryptedAssertion to Response class, but not sure what the best way to do this.

**Comment by i8beef** [comment]
That's not really how you are supposed to use this library. Look at the Wiki here, it explains most of the usage and configuration. Basically, if you are manually building requests and validating responses instead of configuring everything and using the built in handlers, you are in for a world of pain and learning that is far outside the scope here, but you could probably use this as a reference to build your own SAML library then (and steal most of the models because the serialization and schema is pretty involved).

**Comment by flyinggiggs** [comment]
Thanks i8beef!

**Comment by i8beef** [comment]
Look at the top of this page for the words "Wiki"
