### ISSUE TITLE
Metadata Fetcher Crashes App

### ISSUE THREAD

**Issue by Axemasta** [i8beef/SAML2#41]
I wanted to try using the metadata fetcher:

```
<system.webServer>
    <handlers>
        <remove name="SAML2.Protocol.Saml20SignonHandler" />
        <remove name="SAML2.Protocol.Saml20LogoutHandler" />
        <remove name="SAML2.Protocol.Saml20MetadataHandler" />
        <add name="SAML2.Protocol.Saml20SignonHandler" verb="*" path="Login.ashx"
            type="SAML2.Protocol.Saml20SignonHandler, SAML2" />
        <add name="SAML2.Protocol.Saml20LogoutHandler" verb="*" path="Logout.ashx"
            type="SAML2.Protocol.Saml20LogoutHandler, SAML2" />
        <add name="SAML2.Protocol.Saml20MetadataHandler" verb="*" path="Metadata.ashx"
            type="SAML2.Protocol.Saml20MetadataHandler, SAML2" />
    </handlers>
    <modules>
        <remove name="Saml20MetadataFetcher" />
        <add name="Saml20MetadataFetcher" type="SAML2.Saml20MetadataFetcherModule" preCondition="managedHandler" />
    </modules>
    <validation validateIntegratedModeConfiguration="false" />
</system.webServer>
```

In my Saml2 tag:

```
<saml2>
    ...

    <identityProviders metadata="C:\TEMP\sso\metadata">
        <add id="https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/saml2" default="true">
            <endpoints>
                <endpoint type="Metadata" url="https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/federationmetadata/2007-06/federationmetadata.xml?appid=00000000-0000-0000-0000-000000000000" />
            </endpoints>
        </add>
    </identityProviders>
    ...
</saml2>
```

When I run the app:
![server error screenshot](https://user-images.githubusercontent.com/33064621/73278250-3d4c1780-41e3-11ea-9165-28da1345c8f7.png)

I don't know if #37 affects me, but I only have access to Azure AD as an IDP.

**Comment by i8beef** [comment]
There's a race condition in the logging for the IDP metadata file reader stuff. During configuration init, it refreshes the IDP metadata files to initialize their configuration, but if said parsing fails on a file, it tries to log that failure... but the logging isn't inited yet because its still in the process of setting up the configuration. I might just remove this logging in the next release to do away with this.

**Comment by i8beef** [comment]
For your actual issue, this is indicating that its failing in parsing your metadata file. Are there any files OTHER THAN the IDP metadata files in the folder you have pointed to in the idp element metadata attribute?

https://github.com/i8beef/SAML2/wiki/IdentityProviders-Element

**Comment by Axemasta** [comment]
The folder only has the xml in it, the azure federated xml. I think something might have messed up on my end, luckily I had a working set checked in so i just rolled back and this issue disappeared.

**Comment by i8beef** [comment]
Unfortunately, I'm more of a moderator than a maintainer anymore here. I haven't used SAML in almost ten years anymore, so I just try and help others make changes that need made here to keep things running for them.

It is possible that Azure or any other IDP provider started dictating usages that this library doesn't support (SHA256 being just one, apparently that can't be supported without deprecating this library for things below 4.7.2), but extension to support those pieces needs to be community driven here. I will help get things merged, but I can't be the one to really do the work on a lot of it anymore just because I don't have any way to test the changes anymore, and it'd be unfair for me to break everyone with "theoretically this will work" type of changes that go awry.
