### ISSUE TITLE
[Question] Identity Server

### ISSUE THREAD

**Issue by koderi-dp** [i8beef/SAML2#47]
Hi,
Just general question, has someone implemented this or has example with identity server 3, or with owin middleware?

@i8beef  very nice and clean library!

Thanks

**Comment by i8beef** [comment]
IdentityServer3 is an OAuth implementation, not SAML, so that's a different beast.

On a successful authentication handshake, this library will execute a list of configured "Actions", which you can actually write your own for, etc. There's a default set if you don't override that are basically "Cache IPrinciple", "Sign in FormsAuthentication" and "Redirect to redirect url".

The default FormsAuthenticationAction (https://github.com/i8beef/SAML2/blob/master/src/SAML2/Actions/FormsAuthenticationAction.cs) will login to the FormsAuth implementation for the app. I believe the default OWIN FormsAuthentication implementation should still work with that out of the box.
