### ISSUE TITLE
MetadataFetcherModule bug?

### ISSUE THREAD

**Issue by stickeroo** [i8beef/SAML2#49]
I've been trying to get the metadata fetcher to work but I realized after looking through the source, that the metadataFetcher will try to save the the metadata file to an invalid filename when the EntityId of the metadata is formed as a URL or even a URI. Or am I missing something? I am trying to set up the metadataFetcher and it's always failing because it's trying to save the file using the IdentityProvider.Id which has been changed over to use the EntityId from the metadata file ... which in turn is not going to be a valid file format if it's a url.

If I am missing something, my apologies!

Thanks.

**Comment by i8beef** [comment]
Yup. The common use case this was used for was where those URI's were something like my.site.com, not "https://my.site.com". The identityProvider.Id needs to match the EntityId, but the file name I think is actually arbitrary, since on Refresh it's just going to read the contents of files and match any contained metadata to identityProviders via that Id to EntityId equality... 

That is, the use of EntityId / Id as a filename convention is just convenient, I don't see anything saying they have to match as such. In fact, a single document can contain MULTIPLE IDP definitions in it here, so a file isn't necessarily 1:1 with an IDP anyway... I COULD just dump these to a guid named file, but I'd rather sanitize the EntityId I think to keep them tied...

Can you check if the change I just pushed to the master branch here works for you?

**Comment by stickeroo** [comment]
That should do it. Thanks!
