### ISSUE TITLE
PingCompatibilityTest DecryptPingAssertion fails

### ISSUE THREAD

**Issue by dougwebb** [i8beef/SAML2#50]
c:\tmp\pingassertion.txt is missing. Add it to the project and change the path?

**Comment by i8beef** [comment]
That whole test class is marked Explicit and not for general consumption either. As I recall its inherited from the original project as a method to validate Ping assertions for specific consumers. I agree it would have been better if it had a sanitized ping assertion to check instead of being dependent on someone placing their specific assertion somewhere it can read, but I don't actually have access to such a thing. 

If you DO though, Im happy to take a pull request for it.

**Comment by dougwebb** [comment]
Unfortunately no, I don't. I was just trying to use the Run All Tests command, and noted the two failures I've reported.
