### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by jbparker** [i8beef/SAML2#56]
Thanks so much for running the repo & keeping this project going 💪 

Is there anywhere that I might be missing to see release notes & listing out new features, API changes (breaking or otherwise), and bug fixes on each NuGet package version/release?

I got tripped up with a change recently to make the [default state provider cache instead of session](https://github.com/i8beef/SAML2/pull/42/commits/ee27b4c0929369906efd73ad36bb0c81554db337) - a good decision for the library but one that unfortunately my team is tied to right now (PR [here](https://github.com/i8beef/SAML2/pull/42)).

I'm wondering if maybe utilizing [GitHub releases](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository) might help here or if you had any other thoughts about this. I'd also love to help if you had a direction that I could run in.

**Comment by i8beef** [comment]
Well, I've been fairly hands off here for several years, as I tend to live in OAuth land instead of SAML land anymore. I'd actually be open to other maintainers (I guess I'd have to figure out how to transfer to an owning organization or something so it wasn't directly tied to my account anymore; here, at appveyor, and at nuget).

I have some other projects setup to write back a release automatically to GitHub, which will automatically generate some release notes from commit messages, but those are for actual applications, I never bothered to setup it up for things that are just going to be published to NuGet. Maybe its time to explore that as the GitHub releases WILL generate release notes from commit messages to a point. Let me play with it in one of the other projects and see if I can get it generating GitHub releases too.

It'd be nice to get the appveyor build generating nuspec files with the same release notes from commit messages, but they don't support it out of the box, and while it might be possible with post-package scripts it looks like that could be pretty involved.

**Comment by jbparker** [comment]
That makes sense & definitely heard on OAuth. I would be open to helping out, doing primary maintenance, really anything - I'm tied into the project for at least a few more years.

That's awesome about the automatic release writing to GitHub. You're probably right that it's not 100% necessary/warranted, but if it's not too much trouble to look into setting that up (or giving me some pointers on how to help), it would be much appreciated.

**Comment by i8beef** [comment]
Note, I had to put together a new release anyway so I took the time to setup GitHub releases as well for this project. That should resolve this I think?

**Comment by i8beef** [comment]
Closing as the github releases should now include this.

**Comment by jbparker** [comment]
@i8beef thanks for this and sorry for not responding! Totally agree & thanks for seeing this one through.
