### ISSUE TITLE
Choose the Identity Provider

### ISSUE THREAD

**Issue by thisisata** [i8beef/SAML2#63]
Hi,
I am getting the following message from the signon handler->
Please Choose the Identity Provider of your choice from the list below.
And there is noting to choose its not showing any names. Its blank list

**Moreover I should not get this message as I have only one IdP in my configuration and that too has attribute d**efault="true"
![Capture](https://user-images.githubusercontent.com/5272017/100191773-28770800-2f0a-11eb-9d46-e9aaa3e37a53.PNG)

Thanks for ur timely support.

**Comment by i8beef** [comment]
There's something wrong with your config. Since you are having so many issues getting a good config, it might be a good idea to implement a logging provider and look at the debug logs that the library outputs. They may be helpful in pointing out whats wrong with your config.

The error above means it couldn't find ANY properly configured IDP provider. That is, this is returning NULL or MULTIPLE for some reason: https://github.com/i8beef/SAML2/blob/8dfd86989c3a4c7c95e5e0baa850e3f9c7eb532b/src/SAML2/Protocol/Saml20AbstractEndpointHandler.cs#L91
