### ISSUE TITLE
Certificate found in Signature or KeyDescriptor under element "EntityDescriptor" is not trusted

### ISSUE THREAD

**Issue by RoggerFabri** [i8beef/SAML2#8]
I exported my "metadata.xml" to be imported on the Identity Provider partner. When he is importing my "metadata.xml" he gets a: **Certificate found in Signature or KeyDescriptor under element "EntityDescriptor" is not trusted** message. What am I missing? It's the first time I play with SAML2 and OpenAM.

**Comment by i8beef** [comment]
Judging from the error, my guess would be you are using a self-signed cert, and your OpenAM configuration doesn't allow it? So when the metadata is specifying a key for it to use, it is unable to verify the certificate with an authority and is rejecting the whole thing.

I did find a few things by searching for the error you posted about OpenAM an having to import certificates into the Java keystore for it. Can't really help you there though, as that's outside of my experience. You might check with the OpenAM boards to see if someone has a better idea there though.

**Comment by RoggerFabri** [comment]
I kinda understand. I asked my partner about self-signed certificates.
Another thing, on my web.config I have:

`<serviceProvider id="urn:siteware-saml2-unimedbh-SP" server="https://localhost/SIMPLE/">
            <signingCertificate findValue="GeoTrust SSL CA - G3" storeLocation="LocalMachine" storeName="My" x509FindType="FindByIssuerName" />
        </serviceProvider>`

Is it necessary to sign my Service Provider? Shouldn't it be optional?

**Comment by i8beef** [comment]
The SAML 2.0 specification actually specifies signing as a requirement for certain pieces (specifically, when using the POST binding, etc.), and this library follows those specifications. Strictly speaking, if you were using the SOAP bindings, it isn't necessary from what I understand, but I haven't done much on that side.

I will also point out that if you are using an SSL cert as a signing cert, it may not work at all. Certs have to be made with the right usages enabled when you create them, and if I remember right a regular SSL cert is not enabled for signing purposes... I'll repost this suggestion from someone on the old doc pages that might be useful:

I stumbled on the first self-signed cert I tried to use for the SP. Turns out I had made an SSL cert instead of a Signing cert. This is what worked well for my self signed SP cert:

makecert -r -pe -n "CN=your.site.com" -b 01/01/2014 -e 01/01/2030 -eku 1.3.6.1.5.5.7.3.3 -sky signature -ss my -sr localmachine

Read up on what all the params mean here: http://msdn.microsoft.com/en-us/library/bfsktky3

**Comment by RoggerFabri** [comment]
Wonderful. It happens that I did use a SSL cert insted of a Signing cert. I'll think that will solve my problem.
Another question: Does it matter if I create my cert on one machine or another? Can I use the cert I created on my machine in my production server?
Thank you for your help!

**Comment by i8beef** [comment]
Yes, you can. The command above doesn't just create the cert, it installs it to the local machine store (run mmc.exe, add snapin, certifcates, choose machine instead of personal store). You can export the cert from there, just make sure you ALSO export the private key, and that when you install it in production you set the permissions correctly to allow the app to read the private key (This can also be done in MMC).

You can use the makecert command to generate a cert without installing too, but frankly, the command structure for makecert is so cryptic that I can't tell you how, you'll need to go do some research.
